import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import SecondNavbar from "@/SecondNavbar";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <nav className="bg-transparent bg-slate-400 p-4">
              <div className='lg:flex flex-col lg:flex-row  lg:space-x-1 lg:mt-0 mt-4 flex text-xs mx-60'>
                <Link href="/" className="text-blue-900  px-4 py-1 hover:text-gray-500">Investor Relations</Link>
                <Link href="#Projects" className="text-blue-900  px-4 py-1 hover:text-gray-500">Patients’ Stories</Link>
                <Link href="/" className="text-blue-900  px-4 py-1 hover:text-gray-500">Careers</Link>
                <Link href="/" className="text-blue-900  px-4 py-1 hover:text-gray-500">FAQs</Link>
                <Link href="/" className="text-blue-900  px-4 py-1 hover:text-gray-500">Events</Link>
                <Link href="/" className="text-blue-900  px-4 py-1 hover:text-gray-500">
                <img src="https://mg.ced.sa/wp-content/uploads/2024/01/link.png" alt="" className="hover:bg-slate-300"/>
                </Link>
                <Link href="/" className="text-white  px-4 py-1">
                <img src="https://mg.ced.sa/wp-content/uploads/2024/01/fb.png" alt="" className="hover:bg-slate-300"/>
                </Link>
                <Link href="/" className="text-white  px-4 py-1">
                <img src="https://mg.ced.sa/wp-content/uploads/2024/01/twiter.png" alt="" className="hover:bg-slate-300"/> 
                </Link>
                <Link href="/" className="text-white  px-4 py-1">
                <img src="https://mg.ced.sa/wp-content/uploads/2024/01/yt.png" alt="" className="hover:bg-slate-300"/>
                </Link>
                <Link href="/" className="text-white  px-4 py-1">
                <img src="https://mg.ced.sa/wp-content/uploads/2024/01/ig.png" alt="" className="hover:bg-slate-300"/>
                </Link>
                <Link href="/" className="px-4 py-1 text-blue-900 font-sans font hover:text-gray-500">العربية</Link>
            </div>
       </nav>
      <SecondNavbar/>
        {children}</body>
    </html>
  );
}
